config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :randomnumbers
  
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/randomnumber.rb
class Randomnumber < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/randomnumbers_controller.rb
require 'prometheus/client'

class RandomnumbersController < ApplicationController
    @@result = Prometheus::Client::Gauge.new(:demo_gamble_result, 'Result of playing Metric Gamble app.')
    @@users_inthissession = Prometheus::Client::Counter.new(:demo_gamble_users_inthisession, 'Count of users in this session.')
    @@total_users = Prometheus::Client::Gauge.new(:demo_gamble_users_total, 'Count of total users.')

  def index
    @randomnumbers = Randomnumber.order('number DESC').limit(5)
    @counter = 0
  end

  def show
    @randomnumber = Randomnumber.find(params[:id])
  end

  def create
    @randomnumber = Randomnumber.new(randomnumber_params)

    prometheus = Prometheus::Client.registry

    begin
      prometheus.register(@@result)
      prometheus.register(@@users_inthissession)
      prometheus.register(@@total_users)
    rescue Prometheus::Client::Registry::AlreadyRegisteredError => e
    end

    name = params[:randomnumber][:name]

    if name.nil? || name.empty?
      name = 'Anonymous'
      @randomnumber[:name] = name
    end

    @@result.set({name: name}, params[:randomnumber][:number].to_i)
    @@users_inthissession.increment

    @@total_users.set({service: 'metric_gamble'}, Randomnumber.all.count)

    @randomnumber.save
    redirect_to @randomnumber
  end

  private
  def randomnumber_params
    params.require(:randomnumber).permit(:name, :number)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to :controller => 'randomnumbers', :action => 'index'

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/randomnumbers_helper.rb
module RandomnumbersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <!-- <%= image_tag('CaesarPalace1.jpeg') %> -->
  <small>
    <br/>
    Brought to you by
    <a mailto="mia@workday.com">the Monitoring team</a>.
    <br/>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MetricGamble</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/randomnumbers/index.html.erb
<%= stylesheet_link_tag "randomnumbers" %>
<!-- <%= image_tag('CaesarPalace1.jpeg') %> -->

<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">5th Floor Block Party!</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><%= link_to('Play', new_randomnumber_path, method: "get") %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container theme-showcase zero-margin" role="main">
<div class="page-header">
<table>
  <tr>
    <td colspan="2" align="center"><%= button_to 'Play !', new_randomnumber_path, method: "get", :class => "btn btn-lg btn-primary" %></td>
    <br/>
  </tr>
  <tr>
    <td><%= link_to('See Results in Wavefront', 'https://workday.wavefront.com/u/FG8wR91mnY', :class => "btn btn-sm btn-success button") %></td>
  </tr>
</table>
</div>

<div class="page-header zero-margin">
  <h4 width="100px">Leaderboard</h4>
</div>

<div class="row">
<div class="col-md-6">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Result</th>
        <th>Details</th>
      </tr>
    </thead>
    <tbody>
      <% @randomnumbers.each do |randomnumber| %>
        <tr>
          <td><%= RomanNumerals.to_roman(@counter = @counter + 1) %></td>
          <td><%= randomnumber.name %></td>
          <td><%= randomnumber.number %></td>
          <td align="center"><%= link_to('Show', randomnumber_path(randomnumber)) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

<div class="page-header">
  <span class="label label-default">Play as often as you like. Highest score wins a prize!</span>
</div>

<div class="container">
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</div>  <!-- Container -->

app/views/randomnumbers/new.html.erb
<%= stylesheet_link_tag "randomnumbers" %>

<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to('5th Floor Block Party!', root_path, method: "get", :class => "navbar-brand") %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to('Home', root_path, method: "get") %></li>
        <li><%= link_to('Play', new_randomnumber_path, method: "get") %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container theme-showcase zero-margin" role="main">
  <div class="page-header">
    <table>
      <tr>
        <td><h4></h4></td>
      </tr>
    </table>
    </div>

<%= form_for :randomnumber, url: randomnumbers_path do |f| %>
  <p>
    <%= f.label "Your Name" %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.hidden_field :number, :value => rand(10000) %>
  </p>

  <p>
    <%= f.submit "Go!", :class => "btn btn-small btn-primary" %>
  </p>
<% end %>

<div class="container">
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</div>  <!-- Container -->

app/views/randomnumbers/show.html.erb
<%= stylesheet_link_tag "randomnumbers" %>

<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to('5th Floor Block Party!', root_path, method: "get", :class => "navbar-brand") %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to('Home', root_path, method: "get") %></li>
        <li><%= link_to('Play', new_randomnumber_path, method: "get") %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container theme-showcase" role="main">
  <div class="page-header">
    <table>
      <tr>
        <td><h4>Result</h4></td>
      </tr>
    </table>
    </div>

<div class="row">
  <div class="col-md-6">
      <table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Result</th>
  </tr>
  <tr>
    <td><%= @randomnumber.name %></td>
    <td><%= @randomnumber.number %></td>
  </tr>
</table>

<table>
  <tr>
    <td><%= link_to('See Results in Wavefront', 'https://workday.wavefront.com/u/FG8wR91mnY', :class => "btn btn-sm btn-success button") %></td>
  </tr>
</table>
</div>
</div>

<div class="container">
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</div>  <!-- Container -->

app/views/welcome/index.html.erb
<h1>Welcome to the Monitoring Demo Game</h1>

<%= link_to 'Home', controller: 'randomnumbers' %>